# -*- coding: utf-8 -*-
"""Analise de Sentimentos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IX1AJqt83Kfhsvs9qrA48TKfEhYsA0IF
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

data_train = pd.read_csv('/content/moved_imdb_reviews_small_lemm_train.tsv', sep='\t')
data_test = pd.read_csv('/content/moved_imdb_reviews_small_lemm_test.tsv', sep='\t')

display(data_train.head())
display(data_test.head())

x_train = data_train['review_lemm']
y_train = data_train['pos']

tf_idf = TfidfVectorizer()
x_train_vec = tf_idf.fit_transform(x_train)
x_train_vec.shape

lr = LogisticRegression()
lr.fit(x_train_vec,y_train)

x_test = data_test['review_lemm']

x_test_vec = tf_idf.transform(x_test)
x_test_vec.shape

data_test['pos'] = lr.predict(x_test_vec)

data_test.to_csv('predicoes')