CREATE TABLE `scraping`.`paginas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NULL,
  `url` VARCHAR(200) NULL,
  `conteudo` VARCHAR(10000) CHARACTER SET 'utf8' NULL,
  `data` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
